### ISSUE TITLE
[Feature Request]: Sherlock tool, steps listed twice 

### ISSUE THREAD

**Issue by GoldenBanksia** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#1014]
### Name of Feature

Remove second copy of steps

### Priority

Low

### Categories

UX

### Description of Feature

Remove second copy of Step 1, 2 and 3. Keep the first one with the example and the additional spacing.

**Comment by sreedharashwin** [comment]
Before:

<img width="859" alt="image" src="https://github.com/user-attachments/assets/3df5eaa3-6537-4a81-953e-e181026a8593">

After:

<img width="851" alt="image" src="https://github.com/user-attachments/assets/9d881099-f118-43dc-be9d-e4d8ee52c627">
