### ISSUE TITLE
Add tool for smb-enum-users

### ISSUE THREAD

**Issue by Huskehhh** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#12]
https://nmap.org/nsedoc/scripts/smb-enum-users.html

**Comment by j43g3r** [comment]
I'll jump onto this. I will use the current nmap tool as a template.

**Comment by j43g3r** [comment]
Enhanced the tool to do SMB enumeration as a whole as opposed to just enumerating users.
Pull request made for review and merge.

**Comment by Huskehhh** [comment]
Merged in #35
