### ISSUE TITLE
[Feature Request]: Add logo to top right

### ISSUE THREAD

**Issue by Huskehhh** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#38]
### Name of Feature

Add logo

### Priority

Medium

### Categories

UI

### Description of Feature

Could be cool to replace the "Deakin Detonator Toolkit" text in the top left with the logo!

See teams for logos from Hugh

**Comment by PurpleSn0w** [comment]
I quite like the font that is there now. Could we maybe vote on this?

**Comment by Huskehhh** [comment]
Let's bring it up at next week's meeting
