### ISSUE TITLE
[Feature Request]: improvement for Dirb

### ISSUE THREAD

**Issue by Sakada-lim** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#399]
### Name of Feature

improve usability

### Categories

Implementation

### Description
Dirb, a web content scanner, was not installed by default in the Kali DDT GUI and had to be installed manually. Additionally, the GUI lacks a 'scan' button in standard mode, preventing execution of scans. The scan results are also displayed in verbose mode by default, which complicates data analysis.

### Expected Enhancements
1. Include Dirb in the default installation of the DDT GUI.
2. Ensure the 'scan' button is present in both standard and advanced modes.
3. Set verbose mode as optional rather than default to simplify result analysis.

**Comment by Abhijeet-97** [comment]
I have Set the verbose mode as optional to simplify result analysis and it has been verified by team lead. It is working fine now. The error has been fixed.
