### ISSUE TITLE
[Bug]: Crackmapexec

### ISSUE THREAD

**Issue by Sakada-lim** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#401]
### Name of Bug

Unwanted Default timeout

### Description

1. In Standard Mode, the DDT GUI erroneously appends a default timeout value of 60 seconds to the command, which leads to an execution error.
2. Utilizing the Timeout option in Advanced Mode also triggers an error.

### Steps to Reproduce

refer to the PTGUI Project Final Report

**Comment by bradleybogg** [comment]
Issue was resolved without change.
