### ISSUE TITLE
[Bug]: Dmitry

### ISSUE THREAD

**Issue by Sakada-lim** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#403]
### Name of Bug

Syntax error and incorrect require field

### Description
1. The DMitry tool has a syntax error 
2.  non-required fields are mistakenly set as required, indicating a potential script error.

### Steps to Reproduce

refer to the Report

**Comment by v-xl** [comment]
After reading the PTGUI final report, I can see the issues are:
-	Spelling mistakes/grammar errors in the tooltip
-	Dmitry tool not installed in Kali by default
-	Additional errors after running tool through DDT GUI
