### ISSUE TITLE
[Bug]: SMB enumeration

### ISSUE THREAD

**Issue by Sakada-lim** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#410]
### Name of Bug

Incorrect syntax

### What Happened?

The SMB Enumeration feature within the NMAP suite is producing errors due to incorrect command syntax when used via the GUI. Specifically, the GUI introduces additional hyphens into the command line.

### Steps to Reproduce

Refer to the report

**Comment by bradleybogg** [comment]
**Issue:**
There is no handling for a default specified parameter of 'speed'. If nothing is specified, given that it is not a required field, there is no validation. This causes the standalone '-' in the command output.

**Resolution:**
In the latest commit (2070354), a bug has been addressed where the default scan speed was not being set to "T3" in the `onSubmit` function. The issue occurred when the scan speed was not specified in the form values.

**Changes Made:**
- Introduced a check in the `onSubmit` function to ensure the default scan speed is set to "T3" if not provided in the form values.

**Testing:**
Awaiting testing.
