### ISSUE TITLE
[Bug]: DNSEnum

### ISSUE THREAD

**Issue by Sakada-lim** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#412]
### Name of Bug

incorrect syntax/missing feature

### What Happened?

The DNSenum tool within the DDT GUI is experiencing multiple option-related errors:

1. Subdomain Option Error:
   - The GUI misinterprets the subdomain listing, resulting in an incorrect command and subsequent error.

2. User Agents, Blacklist, Whitelist, and Query Type Options:
   - These options generate commands that are not supported by DNSenum, causing errors.

### Steps to Reproduce

refer to the Report

**Comment by bradleybogg** [comment]
Issue:
The component utilises switches and variables outside the scope of original tool found at https://www.kali.org/tools/dnsenum/ and contains invalid syntax.

Resolution:
Removed functionality to confirm with originating tool inside the component.
In the commit(https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/commit/9faed183111285091f09c4ee812b5faff2a5b9d2), the logical issues and functionality was rectified.
In the commit(https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/commit/0a262e146623f625808703abeadc31e4026ecae3), the userguide and instructions were updated to reflect.

Changes Made:
- Code changed to variables conforming with original tool.
- userguide and instructed updated.

Testing:
Awaiting testing.
