### ISSUE TITLE
[Bug]: WPscan

### ISSUE THREAD

**Issue by Sakada-lim** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#415]
### Name of Bug

error when execute

### What Happened?

Executed command in the DDT product error message

### Steps to Reproduce

Refer to the Report

**Comment by bradleybogg** [comment]
Title: WPScan fail to run.

Description: Error presented when attempting to utilise the WPScan component. Handover documentation indicates that the tool will not progress past initial runtime.

To-do: Investigate the cause of the error, create a remediation plan and implement.

Difficulty: Medium.

Team-size: Recommended 1 person.

**Comment by bradleybogg** [comment]
Additional from HOTO docs.

WPScan produces an error when additional options are added to a basic scan. (Basic scan runs as intended.)

Tool tip has grammatical errors. An apostrophe is missing.

**Comment by bradleybogg** [comment]
![image](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/62839826/bca47fc0-6967-4b65-bb6e-3c37ce8ca769)
