### ISSUE TITLE
[Feature Request]: Automated Dependency Resolution for DDT Tools

### ISSUE THREAD

**Issue by Sakada-lim** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#423]
### Name of Feature

Automated Dependency Resolution for DDT Tools

### Priority

Low

### Categories

implementation, development

### Description
A number of tools within the DDT suite lack necessary dependencies for proper operation, which currently requires manual installation by users.

### Problem
- The absence of required dependencies for certain DDT tools results in suboptimal functionality or failure to operate.

### Proposed Solution
- Develop enhanced scripts that automatically detect and install missing dependencies for DDT tools.
- This installation should be designed to run in the background during the initial startup of DDT.

### Goals
- Ensure smooth, uninterrupted operation of all DDT tools by managing dependencies transparently to the user.
- The strategy for the implementation of this automated process remains to be decided.

Refer to #396

**Comment by bradleybogg** [comment]
Issue:
There is no process to automatically resolve dependencies or automated installation of DDT. 

Resolution:
In the commit (https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/commit/55452bb6eb938ca11bd4a5e41cbaa612545e79c2), scripts have been introduced to automate the installation of DDT into a single command. In this same commit I introduce dependencies.json. This file enables developers to update and install specified code at install. 

In the commit (https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/commit/cc3c451b86bf2466b2affdc1356e23fd9a956cd6) I corrected the installation instructions for DDT.

Changes Made:

- Introduced installation script.
- Detached startup script from installation script.
- Created dependencies.json file.

Testing:
Testing has been conducted by Zhen Kang Kok with successful results. Awaiting CI test and post-pull testing.
