### ISSUE TITLE
[Bug]: Rainbow Crack

### ISSUE THREAD

**Issue by bradleybogg** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#498]
### Name of Bug

Rainbow Crack

### What Happened?

Title: Rainbow Crack

Description: The tooltip is copied from another tool and is not accurate..

To-do: Review the subject errors and any images found attached in the Trello card. Find and implement a solution.

Difficulty: Very Easy.

Team-size: Recommended 1 person.

### Steps to Reproduce

Read tooltip

**Comment by CAfitech** [comment]
A pull request that fix this issue has been made and merged.
