### ISSUE TITLE
[Bug]: Fcrackzip does not run because it's not installed

### ISSUE THREAD

**Issue by michaeljpigott** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#526]
### Name of Bug

Fcrackzip does not run because it's not installed

### What Happened?

Fcrackzip does not run. After clicking the start cracking! button, it gets stuck in a loading pattern. 
![image](https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/assets/35479648/8aa40e1b-fd45-4dc9-88f3-65a2d5ce4534)

### Steps to Reproduce

1. Add the file path of an encrypted ZIP file
2. Choose Dictionary as the attack method. 
3. Add a file path to a text file with dictionary terms. 
4. Click Start Cracking! button.

**Comment by russo-christian** [comment]
Issue has been fixed by PR#634 - "407 feature request fcrackzip tools"
