### ISSUE TITLE
[Bug]: Enum4Linux Tooltip Grammar

### ISSUE THREAD

**Issue by bradleybogg** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#532]
### Name of Bug

Enum4Linux Tooltip Grammar

### What Happened?

Description: There is some grammatical errors within the tooltip for Enum4Linux including over capitalisation. Please go through the component tooltip and remove incorrect grammar.

To-do: Review the subject errors and any images found attached in the Trello card. Find and implement a solution.

Difficulty: Very Easy.

Team-size: Recommended 1 person.

### Steps to Reproduce

Review the tooltip and rectify

**Comment by anjojoseph** [comment]
Working on it

**Comment by anjojoseph** [comment]
Updated and raised new pull request
