### ISSUE TITLE
[Feature Request]: Dependency Installer

### ISSUE THREAD

**Issue by bradleybogg** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#540]
### Name of Feature

Dependency Installer

### Priority

High

### Categories

Dependency Installer

### Description of Feature

Issue:

Currently, the installation prompt for components in the application does not behave as expected in cases where the required components are not already installed at runtime.

Expected Behavior:

Ideally, when the application detects that required components are missing, it should trigger a modal prompt asking the user whether they want to proceed with the installation. If the user confirms, the application should then initiate the installation process.

Current Behavior:

However, in its current state, the application does not consistently display the installation prompt when required components are missing. This results in incomplete installations and undermines the user experience by not providing a clear path for resolving missing dependencies.

Steps to Reproduce:

Run the application on a system where some required components are not installed.
Observe the behavior when the application detects missing components.
Impact:

This issue affects the usability and reliability of the application, as it prevents users from easily resolving missing dependencies and fully utilising its features.

Additional Information:

This issue requires further investigation to identify the root cause and implement a robust solution that ensures consistent behaviour across different environments.

**Comment by Jatkin41** [comment]
Testing shows this issue appears to have been resolved, likely through #815
