### ISSUE TITLE
[Bug]: URLSnarf Tooltip

### ISSUE THREAD

**Issue by bradleybogg** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#545]
### Name of Bug

URLSnarf Tooltip

### What Happened?

Description: The tooltip contains grammatical errors.

To-do: Review the subject errors and any images found attached in the Trello card. Find and implement a solution.

Difficulty: Easy.

Team-size: Recommended 1 person.

### Steps to Reproduce

rectify tooltip grammar

**Comment by gangamarx** [comment]
I reviewed this today and updated #568
