### ISSUE TITLE
[Bug]: DNSRecon Tooltip

### ISSUE THREAD

**Issue by bradleybogg** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#546]
### Name of Bug

DNSRecon Tooltip

### What Happened?

Description: The tooltip contains grammatical errors.

To-do: Review the subject errors and any images found attached in the Trello card. Find and implement a solution.

Difficulty: Easy.

Team-size: Recommended 1 person.

### Steps to Reproduce

Check tooltip for grammar

**Comment by russo-christian** [comment]
Closed in unlinked PR# 634 - 546 bug dnsrecon tooltip
