### ISSUE TITLE
[Bug]: Can't open reference links via button in Tauri

### ISSUE THREAD

**Issue by Huskehhh** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#55]
### Name of Bug

Reference link button not working in Tauri

### What Happened?

As a user I want to be able to open a browser with the link to the reference upon clicking the button

### Steps to Reproduce

1. `yarn run tauri dev`
2. Go to "References"
3. Click button to go to reference link

**Comment by PurpleSn0w** [comment]
Which button are you clicking? The green button to right?

**Comment by Huskehhh** [comment]
> Which button are you clicking? The green button to right?

Yep. But now that I give this more thought, it could be because I run the application via WSL. Does it work on your machine? if so this can be closed!

**Comment by PurpleSn0w** [comment]
Yeah works fine in Kali.
