### ISSUE TITLE
[Bug]: Airbase NG Bugfix

### ISSUE THREAD

**Issue by bradleybogg** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#551]
### Name of Bug

Airbase NG Bugfix

### What Happened?

Title: Airbase NG Bugfix

Description:

    Inconsistent component Name.
    Lack of description in the tool tip.
    Missing comments.
    Introduce docs.
    Grammar.
    camelCase naming convention.
    Docstring amendment.
    Introduce runtime dependency checker

To-do: Review the subject errors and any images found attached in the Trello card. Find and implement a solution.

Difficulty: Hard.

Team-size: Recommended 1 person.

### Steps to Reproduce

remediate

**Comment by bradleybogg** [comment]
Linked Branch.
Changes completed. Currently pending authorisation of changes under https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/pull/541 for Runtime dependency.

**Comment by russo-christian** [comment]
Completed in another branch as referred to in PR #559 - 551 bug airbase ng bugfix
