### ISSUE TITLE
[Bug]: feature_description camelCase fix of InstallationModal

### ISSUE THREAD

**Issue by bradleybogg** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#652]
### Name of Bug

 feature_description camelCase fix of InstallationModal

### What Happened?

The installation modal is utilising incorrect variable naming for  feature_description

### Steps to Reproduce

Convert to camelCase #573

**Comment by CAfitech** [comment]
A pull request linked to this issue has been merged which fixes this issue.
