### ISSUE TITLE
[Bug]: InstallationModal continues to appear when the command is different from the name the application

### ISSUE THREAD

**Issue by michaeljpigott** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#692]
### Name of Bug

InstallationModal continues to appear when the command is different from the name the application

### What Happened?

When using the tool RainbowCrack, the InstallationModal keeps appearing because the name of the program (rainbowcrack) is different from the name of command (rcrack). 

When the CommandAvailability tool uses the which command to look for rainbowcrack, it cannot find it despite rainbowcrack being installed and the rcrack command being available. 

It also affects the arpaname tool. 

### Steps to Reproduce

1. Open the rainbowcrack tool. Install rainbowcrack if required. 
2. Go back to the tools menu. Re-select rainbowcrack. 
3. The Installation Modal will still appear despite rainbowcrack being installed.

**Comment by CAfitech** [comment]
This issue has been fixed #825 pull request hence why I am closing this closing the issue.
