### ISSUE TITLE
[Bug]: Arjun tool

### ISSUE THREAD

**Issue by Tillu6** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#706]
### Name of Bug

Arjun tool

### What Happened?
The error  encountering indicates that the ratelimit module is not installed in Python environment. The arjun tool depends on this module, and its absence is causing the tool to fail.

<img width="960" alt="image" src="https://github.com/user-attachments/assets/cdc74342-9b01-4249-8973-065775c3b706">

We can fix this problem by installing the ratelimit module. We can use pip, which is the Python package installer, to do this. Just type the following command in the terminal: pip install ratelimit. Once the ratelimit module is installed, we can try running the arjun command again.
### Steps to Reproduce
Steps to Reproduce
Install the DDT toolkit on Kali Linux.
Launch the DDT toolkit.
open the arjun tool 
Observe the error message

**Comment by CAfitech** [comment]
A pull request linked to this issue has been merged closing this issue.
