### ISSUE TITLE
[Feature Request]: Improve UI for Save output to file button

### ISSUE THREAD

**Issue by michaeljpigott** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#709]
### Name of Feature

Improve UI for Save output to file button

### Priority

Low

### Categories

UI, UX

### Description of Feature

After using a tool, a user is presented with an output filename field and a Save Output to File button: 

![image](https://github.com/user-attachments/assets/04e23952-aa77-41ab-81f2-a38d654c3c25)

It is confusing that both these buttons have a blue background and look very similar. It would be good if one button was designated as the primary button and the other as secondary, and they used different colours. 

Also it would be good if the text for the button was changed to sentence case, e.g. "Save output to file".

**Comment by s223915833** [comment]
Changes done and created a pull request. https://github.com/Hardhat-Enterprises/Deakin-Detonator-Toolkit/pull/741
