### ISSUE TITLE
[Bug]: Traceroute no such file or directory

### ISSUE THREAD

**Issue by JacksonGIThuba** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#727]
### Name of Bug

DDT Traceroute not working

### What Happened?

When attempting to run traceroute for any of the options I get the following output.
$ bash /usr/share/ddt/Bash-Scripts/Tracerouteshell.sh -I 10.0.2.15

bash: /usr/share/ddt/Bash-Scripts/Tracerouteshell.sh: No such file or directory

Process terminated with exit code: 127 and signal code: null

### Steps to Reproduce

Trying to run the tool

**Comment by connorwjordan** [comment]
Issue can be closed by PR #808
