### ISSUE TITLE
Add walkthrough player

### ISSUE THREAD

**Issue by Huskehhh** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#8]
Add the walkthrough video player: 

Useful component: https://mantine.dev/core/aspect-ratio/#video-embed

**Comment by PurpleSn0w** [comment]
@JiatengTao How are you coming along with this player?

**Comment by JiatengTao** [comment]
@PurpleSn0w  I‘m finish it on myside but I need to wait Liam merged the walkthrough page layout so that I can add an example for the player.

**Comment by PurpleSn0w** [comment]
@JiatengTao Good to hear. Are you in communication with @Liamod471 ?
I had a look at his branch ("Walkthrough page design layout"), its months behind the main branch. (Would of updated the project by there is several collisions with current code) 
The application also wouldn't run when I attempted. What branch is he working on? "Walkthrough page design layout" or "liam"?

**Comment by JiatengTao** [comment]
@PurpleSn0w Liam said the PR is already merged, it seems like Jordyn deleted the walkthrough example page during the merging,  I will start working on this and push a PR once I figure these out with Jordyn and Liam.

**Comment by PurpleSn0w** [comment]
@JiatengTao No worries. Can you ask Liam if the two branches I mentioned previously are a work in progress or need to be deleted?
