### ISSUE TITLE
[Bug]: Logo not visible on the app

### ISSUE THREAD

**Issue by lekhk1** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#822]
### Name of Bug

Logo not visible 

### What Happened?

While turning on the DDT app the image of the logo isn't showing up.
![image](https://github.com/user-attachments/assets/ec1a6bdb-9b43-4ba9-bc04-c59f29930163)

### Steps to Reproduce

Just sync the main branch and run the application.

**Comment by michaeljpigott** [comment]
Closing this issue because it was solved by pull request #823
