### ISSUE TITLE
[Bug]: Logo is implemented improperly

### ISSUE THREAD

**Issue by slpysiren** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#837]
### Name of Bug

Logo is implemented improperly

### What Happened?

The DDT logo is added into index.html with inline styling, this causes it to render in a strange position and be persistent on every page, causing UX issues. Suggested fix is to add it into `App.tsx` in the header section as a small icon. An appropriate folder should also be created for `logo.png`.

### Steps to Reproduce

Open the app and scroll up on any page

**Comment by sreedharashwin** [comment]
<img width="1267" alt="image" src="https://github.com/user-attachments/assets/14482bca-7e23-48b5-9bd0-1d9c8cb72a50">

**Comment by connorwjordan** [comment]
Issue can be closed by PR #1004
