### ISSUE TITLE
[Bug]: Unknown variant executeAndReturn, expected one of 'execute', 'stdinWrite', 'killChild', 'open'

### ISSUE THREAD

**Issue by michaeljpigott** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#944]
### Name of Bug

Unknown variant executeAndReturn, expected one of 'execute', 'stdinWrite', 'killChild', 'open'

### What Happened?

When checking for command availability using the checkCommandAvailability function in commandAvailability.ts, DDT is unable to use the execute() method, which results in an error: 

![image](https://github.com/user-attachments/assets/d0781afa-7d4e-4ee4-a61e-a142202ece5a)

This also affects Tshark's Reader functionality: 

![image](https://github.com/user-attachments/assets/848c2e29-b756-4b56-9731-6ee848ee058a)

### Steps to Reproduce

1. Open any tool in DDT. 
2. The installation modal will appear even if the dependency has been installed. 
3. Check the console in developer tools and you will see the error.

**Comment by Oliver2049** [comment]
Hi @michaeljpigott, 
I think i figured out why, it's because of  the version of @tauri-apps/api, I found that our current version got error, but with version 1.5.6, the tool work.
![Screenshot 2024-09-17 225611](https://github.com/user-attachments/assets/ad4b4768-a9f0-4aea-90ab-6ac3d3441d8b)
![Screenshot 2024-09-17 225626](https://github.com/user-attachments/assets/a0d03649-058a-4190-8ff1-c28e83fc3294)

**Comment by michaeljpigott** [comment]
Hi @Oliver2049 I thought DDT is using version 1.5.6???

**Comment by Oliver2049** [comment]
> Hi @Oliver2049 I thought DDT is using version 1.5.6???

Hi @michaeljpigott , on my end, it was 1.3.0 even after pulling, Brennan did try it and worked on his end as well

**Comment by michaeljpigott** [comment]
So what are the step to update it?

**Comment by Oliver2049** [comment]
> So what are the step to update it?

You can run this command npm install @tauri-apps/api@1.5.6 and try if it works on your end.

**Comment by michaeljpigott** [comment]
Yes works for me too. Nice one!!

**Comment by Oliver2049** [comment]
> Yes works for me too. Nice one!!

Nice, then perhaps I will make a pull request for it?

**Comment by michaeljpigott** [comment]
Yes sounds good. Please make a pull request for it.
