### ISSUE TITLE
[Bug]: ExifTool not listed on the References page

### ISSUE THREAD

**Issue by michaeljpigott** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#966]
### Name of Bug

ExifTool not listed on the References page

### What Happened?

The tool Exiftool is not listed on the References page. 

### Steps to Reproduce

1. Open DDT. 
2. Navigate to the References page. ExifTool is not listed.

**Comment by sreedharashwin** [comment]
this is fixed
