### ISSUE TITLE
[Bug]: ExifTool does not show the command and output in the output block

### ISSUE THREAD

**Issue by michaeljpigott** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#967]
### Name of Bug

ExifTool does not show the command and output in the output block

### What Happened?

When running ExifTool, the command and the output are not shown in the output block. 

![image](https://github.com/user-attachments/assets/97e17e00-9c7b-40dd-9b0f-410337d69600)

### Steps to Reproduce

1. Open DDT
2. Navigate to Tools > ExifTool.
3. Enter a file path and metadata tag.
4. Click Run ExifTool
5. Enter your Kali password
6. Waiting for the command to execute. 
7. The command and the output are not displayed in the output block. The only thing shows is "process completed successfully". 

![image](https://github.com/user-attachments/assets/20d94665-88fb-418d-b6ff-a7f002afff32)

**Comment by Samira-fl** [comment]
I'll work on it

**Comment by sreedharashwin** [comment]
This is fixed
