### ISSUE TITLE
[Bug]: Wifite not listed on References page

### ISSUE THREAD

**Issue by michaeljpigott** [Hardhat-Enterprises/Deakin-Detonator-Toolkit#968]
### Name of Bug

Wifite not listed on References page

### What Happened?

The tool Wifite is not listed on the References page. 

### Steps to Reproduce

1. Open DDT. 
2. Navigate to the References page. Wifite is not listed.

**Comment by sreedharashwin** [comment]
I can take this one up. Although, there is no button to self assign
